#!/usr/bin/env php
<?php

include __DIR__ . '/Bootstrap.php';

switch ($argv[1]) {
    case 'migrate':
        migrate();
        break;

    case "make:migration":
        $migration_name = $argv[2];
        $name_array = explode("_", $migration_name);
        $is_creation = $name_array[0] == 'create' ? TRUE : FALSE;
        $auto_name = "";

        for ($i = 1; $i < count($name_array); $i++) {
            if ($i == 1) {
                $auto_name .= $name_array[$i];
            }else {
                $auto_name .= "_{$name_array[$i]}";
            }
        }

        $table_name = isset($argv[3]) ? $argv[3] : $auto_name;

        make_migration($migration_name, $is_creation, $table_name);
        break;

    case 'test':
        test();
        break;
    
    default:
        echo "We do not provide that command bro!";
        break;
}